### ISSUE TITLE
Homepage: reorder testimonials

### ISSUE THREAD

**Issue by ashlchap** [reskillamericans/website#114]
Hi Tobi,

Can you please re-order the testimonials on the homepage (near bottom of page) so that they go in this order:

1. Alexandra Gomez
2. Jalen Harris
3.  Alexandria Baynes
4. Raynell Carmichael
5. Karl Boehringer
6. Ebonnee Hoggard
7. Jarla Kornegay
8. Lorraine Boehringer
9. and the rest can go in any order- please just post them all

 Thank you!

**Comment by mckoss** [comment]
The way this should be done is to add:

```
order = 1
```

or other number to testimonials front-matter.  Then change the testimonials.html shortcode.  Right now it sorts by Name.

https://github.com/reskillamericans/website/blob/f0413d49069f4c2186e21249dcdc9c488a1e5a98/themes/ra-theme/layouts/shortcodes/testimonials.html#L4

That line should be Params.order instead of Params.name, then.

**Comment by mckoss** [comment]
A similar thing was done for the ordering of Team Members.  E.g. see front-matter in:

https://raw.githubusercontent.com/reskillamericans/website/main/content/about/mike-koss/index.md
